### ISSUE TITLE
Is it possible to import others fields then charfields or textfields?

### ISSUE THREAD

**Issue by lbiaggi** [uptick/django-model-import#11]
Hi, 

is it possible to import decimal fields?  if so, how? Right now I'm encountering problems when trying to do this kind of import

**Comment by jarekwg** [comment]
Should work without any need for extra manipulation.

When you subclass ImporterModelForm, just add your decimal fields into the `fields` list in `Meta`, as you do with every other field.

This project validates and saves data by passing it through actual django forms, so the same behaviour applies as does for floatfields/decimalfields there.

If you can provide more specific info, we can take a closer look.

**Comment by lbiaggi** [comment]
Thanks, Jarek
With your explanation, I realize my mistake. thanks!.
I Kinda messed up with form fields types
