### ISSUE TITLE
Error importing user and profile with FlatRelatedField

### ISSUE THREAD

**Issue by tonimarie** [uptick/django-model-import#13]
Data is a OneToOne relationship between User and Profile.
When importing from a CSV, preliminary check shows correct data in correct columns including username.

When selecting "Save" to actually import, blank data is inserted, only one row is created in each table, and no future imports will run (even pre-check) because the blank username is no longer unique.

```
from djangomodelimport import ImporterModelForm,FlatRelatedField

from .models import Profile, User


class UserProfileImporter(ImporterModelForm):
    user = FlatRelatedField(
        queryset=User.objects.all(),
        fields={
            'username': {'to_field': 'username'},
            'first_name': {'to_field': 'first_name'},
            'last_name': {'to_field': 'last_name'},
            'email': {'to_field': 'email'},
        },
    )

    class Meta:
        model = Profile
        fields = (
            'division',
            'location',
            'user',
        )
```

SQL error at SAVE:
`django.db.utils.IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'auth_user_username_6821ab7c_uniq'. Cannot insert duplicate key in object 'dbo.auth_user'. The duplicate key value is (). (2627) (SQLExecDirectW); [23000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]The statement has been terminated. (3621)")`

Thoughts?

**Comment by aidanlister** [comment]
You've got it backwards :)

UserProfileImporter should have a model of User, not Profile.
