### ISSUE TITLE
Many to Many relationship?

### ISSUE THREAD

**Issue by marquicus** [uptick/django-model-import#15]
Hello! It could be nice that FlatRelatedField can handle many to many relationship

**Comment by jarekwg** [comment]
Agreed, would be nice to have m2m support. Not sure about flattening M2Ms onto the form, but at the very least allowing a comma-separated list of ids to be passed in, in order to update an m2m field.

**Comment by jarekwg** [comment]
This is now possible like so (not sure if it was an addition we made, or just a django feature that was discovered heh):
```
tags = ModelMultipleChoiceField(queryset=Tag.objects.all(), to_field_name='name', required=False, widget=NewlineSeparatedM2MWidget)
```

with
```
class NewlineSeparatedM2MWidget(forms.widgets.Widget):
    def value_from_datadict(self, data, files, name):
        if val := data.get(name):
            return val.split('\n')
        return None
```
