### ISSUE TITLE
DateTimeParserField raises AttributeError when the column doesn't exist in the import

### ISSUE THREAD

**Issue by ctassparker** [uptick/django-model-import#2]
Aidan has put forward a solution https://github.com/ABASystems/django-model-import/pull/1 but his concern is; should the non-existent column have gotten to this point? 

Apologies for assigning you all but obviously this wont come up in web. 

hashtagprocess

**Comment by jarekwg** [comment]
Resolved in https://github.com/uptick/django-model-import/commit/653b74932933c9a05cb64638641bcf5b59d6b3c9
